// Generated by ./scripts/generate-api with OpenAPI@1.0.0
// for full api documentation, visit https://github.com/bearyinnovative/OpenAPI
import fetch from 'isomorphic-fetch';
import { getBasePath } from './api';
import { validate } from './_validate';

export default function sessionChannelInfo(payload) {
  return new Promise((resolve, reject) => {
    const err = validate('/session_channel.info', payload);
    if (err) {
      return reject(err);
    }

    const opts = {
      headers: {'Accept': 'application/json'},
      method: 'GET',
    };
    opts.query = payload;

    const api = getBasePath('https://api.bearychat.com/v1') + '/session_channel.info';
    return fetch(api, opts);
  });
}